### ISSUE TITLE
'No Album' Tracks For Just One Artist

### ISSUE THREAD

**Issue by pkcrawford** [CDrummond/lms-material#147]
When I click the following:
Home Screen>Artists>'artist_name'>'No Album'
I am presented with all tracks in my collection that are not a part of an album, instead of just the tracks from the artist I previously selected.  Is there a way to only show the tracks for the artist I have selected?

**Comment by CDrummond** [comment]
Track listing comes from LMS. Do you see this in the default webUI?

**Comment by CDrummond** [comment]
Sorry, I dont see this issue. I tagged 4 tracks, each with a different artist, no album, and no album-artist. If I configure LMS to "Use single, configurable list of all artists" then they are grouped under "Artists / Various Artists / No Album". If I configure LMS to "Use two separate lists for Album Artists and Artists", then I see "All Artists / TestArtist1 / No Album / track" - as expected, and what you are asking for.

**Comment by CDrummond** [comment]
Also, please setting Material to use 'Categories from server' - as this is what the next version will exclusively use.

**Comment by pkcrawford** [comment]
Hey Craig, the answer to your first question is yes, it works in the default webUI.  I see the link path as you describe ("Artists / Various Artists / No Album"), but when I click on 'No Album' under the artist I have selected, I am seeing what looks like all of the tracks in my collection that have 'No Album' assigned (I call these my singles/45s tracks).  When I do the same thing through the default webUI, I only see the tracks related to the artist I am browsing.

**Comment by CDrummond** [comment]
As stated, this is working for me - so I'm going to need more info. First of all I assume you did not mean "Artists / **Various Artists** / No Album"

Please run Material, in a desktop browser, as follows:

1. http://HOSTNAME:9000/material/desktop?debug=json
2. Open your browser's developer tools
3. Go to the 'Console' tab within the developer tools
4. Using material, navigate to the invalid track listing
5. Copy ALL of the text in the 'Console' tab, and attach to this issue

This will let me know what messages material sends, and what responses it receives.

Also - are you grouping artists? One list of two?

**Comment by pkcrawford** [comment]
Here is the json log:
[json.log](https://github.com/CDrummond/lms-material/files/3612692/json.log)

Browse Artists is set to 'Use single, configurable list of artists'
Compilations settings is 'List compilation albums under each artist'

Let me know if there is any other information you requires.  Thanks.

**Comment by CDrummond** [comment]
Thanks for this. I _think_ I know what the issue is. Do you have "Show all albums and tracks for an artist" set as the value for "Filter Contributor Roles at the Album & Track Level" (in settings "My Music" in default web UI)???

**Comment by CDrummond** [comment]
Any chance you can use the version from this repo? i.e. to a git checkout?

A rough guide to using the git version:
1. Install 'git'
2. Run command: git clone https://github.com/CDrummond/lms-material.git
3. Uninstall exiting MaterialSkin
4. Copy the 'MaterialSkin' folder from your 'git clone' into the 'Plugins' folder of your LMS install. This should be the non-cache Plugins folder. The 'Information' page of the default web UI should list the folder locations
5. Restart LMS
6. Hard-reload Material in your browser - also pass "clearcache=true" as a URL parameter - e.g. `http://HOSTNAME:9000/material/desktop?clearcache=true`

**Comment by CDrummond** [comment]
Closing as issue is fixed for next release (1.0.0)

**Comment by pkcrawford** [comment]
Craig, you move fast!  Yes, the Filter Contributor Role is set to "Show all albums and tracks for an artist".  I think I'll wait for the next release instead of trying the git version.  Thanks so much for looking into this.

**Comment by pkcrawford** [comment]
I don't know what I am doing wrong, but when I try doing this using LMS Version: 7.9.2 - 1568726655 and Material Skin (1.0.1) I am still get a list of all of my tracks without an album.  I can confirm that this does not happen with the default UI.   In the default UI, I only see the tracks for the artist I previously selected.

**Comment by CDrummond** [comment]
As stated, I would need more info. Did you try the above to clear Material's cache? `http://HOSTNAME:9000/material/desktop?clearcache=true`

**Comment by pkcrawford** [comment]
I am now using Material Skin (vDEVELOPMENT).  I followed your instruction and here is the new json log file:
[1569239785242.log](https://github.com/CDrummond/lms-material/files/3641994/1569239785242.log)

**Comment by CDrummond** [comment]
Thanks for the log file, and for using the dev version - makes things easier. Can you update your dev checkout, re-install, clear Material's cache (both browser cache and via URL above). and see if this is now resolved?

**Comment by pkcrawford** [comment]
Works as expected now.  Here is another log for reference:
[1569297211760.log](https://github.com/CDrummond/lms-material/files/3645132/1569297211760.log)

**Comment by CDrummond** [comment]
Thanks for the confirmation.
