### ISSUE TITLE
Top of page cut off in Safari

### ISSUE THREAD

**Issue by mforkel** [CDrummond/lms-material#589]
I am using Material Skin 2.9.4 with LMS 8.2.0 to control a Squeezebox from an iPad with iPadOS 15.

When I wake up the iPad, go to Safari and select the (previously opened) server page, it looks something like this:

![grafik](https://user-images.githubusercontent.com/1212429/167246664-4d6f951f-4a0c-4e05-ae8e-59b721d88425.png)

Only after reloading the page, the top part is visible as well:

![grafik](https://user-images.githubusercontent.com/1212429/167246701-eaaef261-50f3-42be-95e8-8186bdfe02ad.png)

This is not a new problem. I already occurred with older versions of Material Skin, LMS, and iPadOS.

**Comment by CDrummond** [comment]
Looks like a Safari issue to me. Sorry, I have no iPad.

**Comment by mforkel** [comment]
Anything I can do to help you debug this?

**Comment by CDrummond** [comment]
Unless you know how to debug webapp on iOS, no idea. Sorry, but I have no apple products, and am not a web developer, so no experience of this myself.

**Comment by mforkel** [comment]
Ok, I'm afraid I can't help then. May be somebody else will pitch in (keeping my fingers crossed). Thanks for the quick response, though!

**Comment by CDrummond** [comment]
Does this only happen on the desktop layout? Try setting Material to mobile and see if this also has issues. (Top right three dotted button, Setting, Interface, Application layout).

Did Material used to work OK on much older versions? What you could try is manually installing older versions until it works (e.g. go back to 2.0.0 see if it works, if it does try 2.5.0, if not try 1.5.0, etc). (NOTE: With iOS you _might_ need to clear Safari's cache each time to ensure the page is full re-loaded). Tracking down where the issue appeared would allow me to have some idea of what might be causing this - I can look at a the differences between versions.

**Comment by mforkel** [comment]
The problem does not happen with the mobile layout.

Checking older versions will take some more time. The problem only happens when Safari reloads the page (after initially showing a blank page) when I wake up the iPad in the morning. May be that is a hint by itself? I assume after a certain amount of time Safari considers the content invalid and forces a reload. Is that timeout an attribute of the Material page that I can influence? Then I could speed up the test cycle.

**Comment by CDrummond** [comment]
As a **very** hacky work-around you could try editing server.js and change the following lines (84 ... 91) from:

```
setInterval(function() {
    var currentTime = (new Date()).getTime();
    if (currentTime > (lastTime + (2000*2))) {
        bus.$emit('refreshStatus');
        bus.$emit('checkNotifications');
    }
    lastTime = currentTime;
}, 2000);
```

to 

```
setInterval(function() {
    var currentTime = (new Date()).getTime();
    if (currentTime > (lastTime + (2000*2))) {
        bus.$emit('refreshStatus');
        bus.$emit('checkNotifications');
        var isDesktopLayout = store.state.desktopLayout;
        if (isDesktopLayout && IS_IOS) {
            bus.$emit('changeLayout', !isDesktopLayout);
            setTimeout(function () { bus.$emit('changeLayout', isDesktopLayout); }, 25);
        }
    }
    lastTime = currentTime;
}, 2000);
```

Every 2 seconds Material checks the current time. If there is more than 2 seconds between this and the previous time Material assumes its been woken from a sleep so refreshes its status, etc. The change above will cause Material to swithc to mobile and back to desktop - which should work-around the issue. But is not really nice. If the above does work, then please also try:

```
setInterval(function() {
    var currentTime = (new Date()).getTime();
    if (currentTime > (lastTime + (2000*2))) {
        bus.$emit('refreshStatus');
        bus.$emit('checkNotifications');
        if (store.state.desktopLayout && IS_IOS) {
            setLayout(true);
            bus.$emit('layoutChanged');
        }
    }
    lastTime = currentTime;
}, 2000);
```
...does the above also work?

**NOTE** You will need to checkout Material from git for the above, as the release code is 'minified' and cannot be easily edited. You will also need to clear safari's cache, and hard-reload the page (perhaps use private browsing tabs?) to ensure that safari uses the latest code, not its cached copy.

**Comment by mforkel** [comment]
Reporting the issues seems to have partially resolved it :-)

For the last two days, the problem has not occurred. (Before that, every morning.) I don't know what has changed. At least I haven't applied your patch (thanks!), because I wanted to start testing older versions. But obviously I can't do that while the current version is working.

**Comment by CDrummond** [comment]
@mforkel Any updates? Is this now working? Has a Safari update fixed this?

**Comment by mforkel** [comment]
Thanks for checking back. I'm now using iPadOS 15.5 and Material Skin 2.9.6, and the situation has not changed.

It seems that the problem only occurrs if Safari determines that after 12 (just a guess) hours the displayed page(s) are "too old". In that case, Safari redisplays its entire contents, i.e. everything goes blank (black with my selection of the dark theme) except for the address bar. Safari then displays the page again, but seems to neglect the tab height. I guess what is missing from the top of the page is "hidden" underneath the tab(s). While this (re)display cuts off the top of the page, a regular page refresh displays the complete page.

I have not seen this phenomenon with pages other than Material Skin. But I'm afraid I don't have any clue what might be causing it.

**Comment by CDrummond** [comment]
OK. Would you be able to edit some HTML code? Can you edit `MaterialSkin/HTML/material/index.html` and change line 64 from:

```
    <div v-if="desktopLayout" class="lms-desktop-toolbar-pad"></div>
```

to
```
    <div v-show="desktopLayout" class="lms-desktop-toolbar-pad"></div>
```

This changes a `v-if` to `v-show`. You will also need to restart LMS, clear Safari's cache, and fully reaload the page. Not sure if this will make much difference, but `v-show` is used for other elements which seem to work so this _might_ help.

**Comment by CDrummond** [comment]
I've just released 2.9.7 with the above change. I'm doubtful it'll make any difference, but causes no harm.

**Comment by mforkel** [comment]
You are too fast :-) I had just made the change locally.

I'll report if that (or 2.9.7, once it has trickled down to my server) changes anything. Since I don't know how to force the error, that will a  couple of days.

**Comment by mforkel** [comment]
Unfortunately, the change does not fix the problem.

I had upgraded to 2.9.7 yesterday and opened Material Skin in Safari. The page looked fine. This morning, I switched to Safari and the page still looked fine. But when I switched to Safari again 15 minutes later after using another app, Safari rebuild all tabs. Material Skin was the front tab and its top was cut off as before.

**Comment by CDrummond** [comment]
Yeah, I did state I thought it would not fix the issue. Sorry, but there is not much I can do here. I have no iPad, so all I can suggest is you try the modifications mentioned previously.

I have Material loaded in a Chromium webapp window almost constantly, and never seen this issue.

**Comment by CDrummond** [comment]
Can you try the following version? Unzip the contents of this file over the top of your existing _MaterialSkin_ folder in your LMS's plugins folder. Restart LMS, clear Safari cache, full reload, etc.

[lms-material-test.zip](https://github.com/CDrummond/lms-material/files/8986391/lms-material-test.zip)

p.s. When you tried 2.9.7 did you clear Safari's cache and hard-reload? If not its possible Safari was using a cached version of 2.9.6

**Comment by mforkel** [comment]
I'll give it a try.

When I applied the change you suggested, I did clear Safari's cache. But what is involved in a hard-reload?

I searched the net a little. Other people seem to have problems with Safari cutting off contents as well. Does [this suggestion](https://stackoverflow.com/questions/11993836/prevent-ipad-mobile-safari-from-cutting-off-content-via-css) apply in any way?

**Comment by CDrummond** [comment]
I guess safari on iOS does not have "hard-reload", so closing tab, clearing cache, and re-loading _should_ be enough. /just want to make 100% sure Safari is using the test version, and not some version from cache.

**Comment by mforkel** [comment]
After Settings > Safari > Clear History and Website Data Safari (or, in my case, its Germain equivalent) opening Safari brings up the favorites page. From which I opened the Material Skin page. I guess that should be ok then. 

So far everything looks fine. But with this kind of problem, you might see evidence that it is still there. But you can't be sure it is gone. I'll wait and report.

In any case, thanks for your support!

**Comment by mforkel** [comment]
I'm sorry to say that the test version does not eliminate the problem.

**Comment by CDrummond** [comment]
Hmmm... OK, try this version instead:

[lms-material-test2.zip](https://github.com/CDrummond/lms-material/files/9016966/lms-material-test2.zip)

...again, need to clear cache, etc.

**Comment by mforkel** [comment]
Thanks. I have installed the new test version and will report.

**Comment by CDrummond** [comment]
I've release 2.9.8 which contains this change, plus a bug fix for missing menu items.

**Comment by mforkel** [comment]
Thanks, I'll upgrade and report.

**Comment by CDrummond** [comment]
@mforkel I'm apprehensive to ask, but... any updates?

**Comment by mforkel** [comment]
So far, so good :-) This morning for the second time the page was displayed correctly after a reload from the all black start. I've seen another phenomon twice though over the last days: Instead of the whole page, only an enlarged left column (where the favorites or recordings are listed) was shown.

**Comment by CDrummond** [comment]
Great, so this issue is fixed.

As to the other - did the browse display take the whole width? Are you sure mobile view was not active? Was the hide queue button shown in regular text colour?

**Comment by mforkel** [comment]
> Great, so this issue is fixed.
Well, I hope so. But the problem doesn't show up reliably enough to be absolutely sure.

> As to the other - did the browse display take the whole width? Are you sure mobile view was not active? Was the hide queue button shown in regular text colour?
Yes, whole widht, and no, I don't use mobile view. But I have to ask: What is the "hide queue button", please?

**Comment by CDrummond** [comment]
In the main toolbar is a icon that has 4 lines and a musical note - this can be used to toggle the display of the queue. If it is "blue" (colour will change dependent on your settings) then the queue should be visible.

**Comment by mforkel** [comment]
Thanks, found it. Right now, the hide queue button is blue and the queue is visible. As you might have already guessed, I don't use it. I'll check whether it is visible and what color it has if the problem should occurr again. From memory I would say the toobar wasn't visible at all, but I'm not sure.

**Comment by mforkel** [comment]
The hide queue button is not visible. What is visible from top to bottom are the Safari menu bar. the left half of the upper Material Skin menu bar (logo and device only, no volume or any of the icons to the right), the lower Material skin menu bar (left entry only, no icons), and the left column (My Music, ...). No footer (play icons, titel, ...).

**Comment by CDrummond** [comment]
Well, I give up. Sounds like a Safari issue to me - as this does not occur elsewhere.

Sorry, but closing.

**Comment by mforkel** [comment]
I understand, thanks for your support, just a minor glitch in a very good software.

**Comment by CDrummond** [comment]
OK, one last test. Please try the attached version. This has a version of the work-around from above. Basically Material checks the time every 2 seconds, if the gap between this and the last time is greater than 4 seconds Material assumes the computer has been awoken from sleep and so refreshes a few things. This code has been updated to also check if running on iOS, desktop view, and time gap is greater than 15 seconds. If so, then the view is set to mobile, and immediately back to desktop. This causes a _slight_ flicker for me, but hopefully works-around the issue. Please install and try. (Again, ensure safari's cache is cleared and page is fully reloaded).

[lms-material-test3.zip](https://github.com/CDrummond/lms-material/files/9077564/lms-material-test3.zip)

**Comment by mforkel** [comment]
Thanks for giving it another try. If it's ok with you, I'd still like to wait a little bit before switching to the new test version. Over the last couple of days, I have experienced none of the two problems.

**Comment by mforkel** [comment]
I have not seen any glitches with version 2.9.8 after my initial report. Now upgraded to 2.10.0. Thanks again!
